### ISSUE TITLE
Add way to upload file with metadata

### ISSUE THREAD

**Issue by DoumanAsh** [yoshidan/google-cloud-rust#103]
Seems like API allows to upload file with metadata by multipart.
`reqwest` provides some basic support for multiparts via `multipart` features which adds `mime_guess` dependency.

If I'm correct that's all there to it, would you mind having it?

**Comment by johnrichardrinehart** [comment]
What's the distinction between this issue and https://github.com/yoshidan/google-cloud-rust/issues/98 ?

**Comment by DoumanAsh** [comment]
None?
I didn't notice your issue so stop bothering me

**Comment by johnrichardrinehart** [comment]
All good. Wasn't trying to bother you. Just a real question.
