### ISSUE TITLE
Does this lib support gcp workload identity?

### ISSUE THREAD

**Issue by alexandrst88** [yoshidan/google-cloud-rust#109]
HI! After this merged, does lib supports gcp  workload identity https://github.com/yoshidan/google-cloud-rust/pull/105? Thanks

**Comment by yoshidan** [comment]
We have confirmed that the [GKE workload identity](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity) works.
We have not tried integration with AWS or Azure via workload identity. 
If it does not work with google-cloud-auth, you can create your own crate that implements google-cloud-token.

**Comment by alexandrst88** [comment]
thank you
