### ISSUE TITLE
Set content type

### ISSUE THREAD

**Issue by PatrickHeneise** [yoshidan/google-cloud-rust#110]
Thanks for providing this library! I've managed to set up a file down- and upload based on your [latest changes from today](https://github.com/yoshidan/google-cloud-rust/commit/c43665f69bc47a4dd1cad28b71a3a7f38139eea1).

Is there a way to set the Content Type other than `application/octet-stream` based on the filename/extension?

**Comment by yoshidan** [comment]
Yes there is . You can set Content-Type as [followoing code](https://github.com/yoshidan/google-cloud-rust/blob/main/storage/src/http/storage_client.rs#L2939).
```
let mut media = Media::new("test1");
media.content_type = "text/plain".into();
let uploaded = client.upload_object(
       &UploadObjectRequest {
            bucket: bucket_name.to_string(),
             ..Default::default()
       },
        vec![1, 2, 3, 4, 5, 6], 
        UploadType::Simple(media), 
        None
).await;
```

**Comment by PatrickHeneise** [comment]
Thanks. Sorry for opening an issue, didn't think it was that easy.
