### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GAX(InvalidEmulatorHOST(""))', src/main.rs:15:45

### ISSUE THREAD

**Issue by lasagar** [yoshidan/google-cloud-rust#124]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GAX(InvalidEmulatorHOST(""))', src/main.rs:15:45. How do i resolve this? I ran the code as is

**Comment by lasagar** [comment]
I am using Google-cloud-pubsub, can you point me to that documentation with
the info using client config

**Comment by yoshidan** [comment]
Here is the `google-cloud-pubsub` readme.
You must use google-cloud-default together as described in the readme.
https://github.com/yoshidan/google-cloud-rust/tree/main/pubsub

I am sorry but the method of using emulator is not described in the documentation and should be clearly stated.
google-cloud-pubsub reads environment variables at the following location
https://github.com/yoshidan/google-cloud-rust/blob/1043d7019daed0c7c4a0c178a3fbdddf98f14015/pubsub/src/client.rs#L32

**Comment by lasagar** [comment]
Hey, Thank you. How do I publish/subscribe to pubsub without using emulator. Can you pls help me with it. Thank you

**Comment by yoshidan** [comment]
It looks that no credentials is found.  

You must set [google credential file](https://cloud.google.com/iam/docs/keys-create-delete#creating) into os env 'GOOGLE_APPLICATION_CREDENTIALS' before calling `with_auth`.
`ClientConfig.default().with_auth()` reads the `project_id` from `GOOGLE_APPLICATION_CREDENTIALS` outside the GCP without emulators.
```
export GOOGLE_APPLICATION_CREDENTIALS=/path/your_credentials.json
```

```
let config = ClientConfig::default().with_auth().await.unwrap();
let client = Client::new(config).await.unwrap();
```

**Comment by lasagar** [comment]
Thank you, I had set the GOOGLE_APPLICATION_CREDENTIALS, still the same. When I print the config, its showing me the project_id is None. 


ClientConfig {
    pool_size: Some(
        4,
    ),
    project_id: None,
    environment: GoogleCloud(
        ,
    ),
    endpoint: "pubsub.googleapis.com",
}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ProjectIdNotFound', src/main.rs:16:45

**Comment by lasagar** [comment]
Also in the client.rs, I noticed that its looking for PUBSUB_EMULATOR_HOST instead of GOOGLE_APPLICATION_CREDENTIALS. 

/// ClientConfigs created by default will prefer to use `PUBSUB_EMULATOR_HOST`
impl Default for ClientConfig {
    fn default() -> Self {
        let emulator = var("PUBSUB_EMULATOR_HOST").ok();
        let default_project_id = emulator.as_ref().map(|_| "local-project".to_string());
        Self {
            pool_size: Some(4),
            environment: match emulator {
                Some(v) => Environment::Emulator(v),
                None => Environment::GoogleCloud(Box::new(NopeTokenSourceProvider {})),
            },
            project_id: default_project_id,
            endpoint: PUBSUB.to_string(),
        }
    }
}

Is my understanding correct? Pls suggest so that i can test the publish message and subscribe message later

**Comment by lasagar** [comment]
Thank you, tried hard coding now and it worked.

**Comment by open-schnick** [comment]
If you are still having trouble the documentation was updated in #126

**Comment by drewgatchell** [comment]
> If the `project_id` is empty even though `with_auth` is called, then the `project_id` in the credentials file is empty.

This happens with `gcloud auth login --update-adc`

Credentials File ends up as:
```
{
  "client_id": <client_id>,
  "client_secret": <client_secret>,
  "refresh_token": <refresh_token>,
  "type": "authorized_user"
}
```

**Comment by yoshidan** [comment]
If the credentials does not include the project_id, the project_id must explicitly set the project_id.
```rust
let mut pubsub_config = google_cloud_pubsub::client::ClientConfig::default().with_auth().await?;
pubsub_config.project_id = Some(xxx);
```
