### ISSUE TITLE
Wouldn't it make sense for the Storage Client to be clonable?

### ISSUE THREAD

**Issue by open-schnick** [yoshidan/google-cloud-rust#134]
Currently the [`Storage Client`](https://docs.rs/google-cloud-storage/0.10.0/src/google_cloud_storage/client.rs.html#38) is not `clone`.
It also cannot be derived directly because [`ServiceAccountClient`](https://docs.rs/google-cloud-storage/0.10.0/src/google_cloud_storage/http/service_account_client.rs.html#9) is also not `clone`
Can we derive that on these two structs or does that introduce sideeffects?
I would imagine that duplicating the `ServiceAccountClient` means duplicating the authentication logic.
Thoughts @yoshidan?

**Comment by yoshidan** [comment]
Since the Client and its children have not a few fields, for example, I think the allocation load to Clone for each request may be large.
Currently, though, we would use Arc as follows,

```rust
let client = Arc::new(client)
let client_per_each_request = client.clone()
```

I think it would be nice to have Arc inside as well as other components.
```rust
#[derive(Clone)]
pub struct Client {
    inner: Arc<InternalClient>
}

struct InternalClient {
    default_google_access_id: Option<String>,
    default_sign_by: Option<SignBy>,
    storage_client: StorageClient, default_account_client: Option<String>,
    service_account_client: ServiceAccountClient
}
```

**Comment by open-schnick** [comment]
Sorry for the late response, 
I wrapped the Client myself in an Arc.
Thanks for your feedback :)
