### ISSUE TITLE
Publishing a message succeeds but causes an error: "failed to notify : id="

### ISSUE THREAD

**Issue by julianbraha** [yoshidan/google-cloud-rust#159]
My publisher is successfully publishing messages, and my subscriber is receiving them. But every time a messaged is published, the publisher has an error: "failed to notify : id=<some long string of numbers>". What causes this error?

**Comment by yoshidan** [comment]
Please show me your code.

**Comment by julianbraha** [comment]
I've found the problem. After publishing the message, I was not using `awaiter.get().await;` like in the publishing example. Adding this solved the problem.
