### ISSUE TITLE
Spanner interleaved tables?

### ISSUE THREAD

**Issue by gibssa** [yoshidan/google-cloud-rust#192]
Hi,

I noticed `google_cloud_spanner` supports [multiple reads](https://docs.rs/google-cloud-spanner/latest/google_cloud_spanner/#multiple-reads):
```
    let mut stmt = Statement::new("SELECT * , \
            ARRAY (SELECT AS STRUCT * FROM UserItem WHERE UserId = @Param1 ) AS UserItem, \
            ARRAY (SELECT AS STRUCT * FROM UserCharacter WHERE UserId = @Param1 ) AS UserCharacter  \
            FROM User \
            WHERE UserId = @Param1");
```

Suppose we wanted to add [one more interleaved Spanner table](https://github.com/yoshidan/google-cloud-rust/blob/main/spanner/tests/ddl/schema.sql):
```
CREATE TABLE UserItemHistory
(
    UserId STRING(36) NOT NULL,
    ItemId INT64 NOT NULL,
    UsedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)
) PRIMARY KEY(UserId, ItemId, UsedAt), INTERLEAVE IN PARENT UserItem ON DELETE CASCADE;

```

Is this possible with this crate?

**Comment by yoshidan** [comment]
Yes.  Here is the example.
https://github.com/yoshidan/google-cloud-rust/blob/293590f23056fd65b4aac0b7db0aae472af15323/spanner/tests/transaction_ro_test.rs#L108

**Comment by yoshidan** [comment]
Yes.  Here is the example.
https://github.com/yoshidan/google-cloud-rust/blob/293590f23056fd65b4aac0b7db0aae472af15323/spanner/tests/transaction_ro_test.rs#L108

**Comment by gibssa** [comment]
Thank you!
