### ISSUE TITLE
[question] contribution to more GCP services (container registry, etc)

### ISSUE THREAD

**Issue by benjaminch** [yoshidan/google-cloud-rust#198]
Hello there !

First of, thanks a lot for this library, the API is very pleasant to use :)

I would want to use this library but I would miss couple Google components: container registry, kubernetes and eventually some managed DB services).
Are you open to receive contributions integrating such components?

Cheers !

**Comment by yoshidan** [comment]
Yes, we would like to add other components as needed and would appreciate your contribution.

**Comment by benjaminch** [comment]
Thanks a lot :)
