### ISSUE TITLE
Expose an endpoint to override pubsub domains

### ISSUE THREAD

**Issue by andresmargalef** [yoshidan/google-cloud-rust#25]
The java sdk [here](https://github.com/googleapis/java-pubsub/blob/e5555633bf4dc4ee543eb2596bafacdd78ea9d16/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L850) add support for endpoint override.
This is a great feature to prevent internet traffic to pubsub from my machines when a google private service connect is configured.

Right now the [connection manager](https://github.com/yoshidan/google-cloud-rust/blob/7d4a3ff271f6f7530152a6b50fca8eda0ebf1825/pubsub/src/client.rs#L65) is internal and the domain is hardcoded as 'static &str [here](https://github.com/yoshidan/google-cloud-rust/blob/7d4a3ff271f6f7530152a6b50fca8eda0ebf1825/pubsub/src/apiv1/conn_pool.rs#L5)

Is there a chance to add this feature?

**Comment by yoshidan** [comment]
Thank you for your suggestion. I will make endpoint mutable in order to use PSC.
