### ISSUE TITLE
create_token_source function deprecated, recommended TokenSourceProvider not public.

### ISSUE THREAD

**Issue by clement-chaneching** [yoshidan/google-cloud-rust#250]
Hello,

I m trying to implement the google-cloud authentication module in [rattler](https://github.com/mamba-org/rattler) for pixi to automatically pick up the authentication for our private conda channel hosted on a GCS Bucket.

Everything works perfectly fine, but I have this warning that the create_token_source  function has been deprecated, and the recommended TokenSourceProvider is not public, so I cannot implement the recommended : DefaultTokenSourceProvider 

Is there a workaround that I m not aware of?  Are you planning to update the documentation soon?

Thanks for your help!

**Comment by clement-chaneching** [comment]
Nevermind, the issue is just because I was testing with the latest main, not the latest tag.

**Comment by yoshidan** [comment]
sorry for late response.

`TokenSourceProvier` in main branch is now public. 
https://github.com/yoshidan/google-cloud-rust/blob/ff65df43a1bb8ffd6bfaa3c047186ba137345a79/foundation/token/src/lib.rs#L12

`TokenSourceProvier` is not in `google-cloud-auth` but in `google-cloud-token` crate.

In [this case](https://github.com/mamba-org/rattler/pull/605/files#diff-0975d0303485355139783b20dd69ed2b4a2a0b9f277f91fb39e6c3c68c5bc570R117) it seems you can use `google_cloud_auth::token::DefaultTokenSourceProvider::new` directly.
