### ISSUE TITLE
Request for Migration to reqwest ^0.12.0 in google-cloud-storage Dependency

### ISSUE THREAD

**Issue by LenWilliamson** [yoshidan/google-cloud-rust#251]
I'm reaching out regarding the `google-cloud-storage` crate, specifically its dependency on `reqwest`. Currently, the crate relies on `reqwest` version `^0.11.0`.

However, there is a need for compatibility with `reqwest` version `0.12.0` in my crate.

Would it be possible for you to consider migrating the `google-cloud-storage` crate to use `reqwest` version `0.12.0` in an upcoming release? I understand that this may involve some effort, and I am willing to assist in any way I can, whether it's testing, providing feedback, or contributing code changes.

**Comment by yoshidan** [comment]
It is our policy to use the latest versions of dependent libraries. Therefore, even if compatibility is broken, we will update to the latest version upon request.
We welcome updates to `reqwest`, as you have requested 0.12.
