### ISSUE TITLE
Support for pubsub publish in bulk

### ISSUE THREAD

**Issue by andresmargalef** [yoshidan/google-cloud-rust#26]
At work for high performance we have apis that operates in bulk not in single message.
Maybe adding a new method in publisher that support an iterable of ReservedMessages could be useful to prevent send one by one message to the channel. Maybe an enum Reserved::Multi and Reserved::Single could be useful to detect if is single or not for the matching [here](https://github.com/yoshidan/google-cloud-rust/blob/7d4a3ff271f6f7530152a6b50fca8eda0ebf1825/pubsub/src/publisher.rs#L224).

**Comment by yoshidan** [comment]
Thank you for your proposal. I will add the implementation.

**Comment by ditsuke** [comment]
Should this issue be closed?
