### ISSUE TITLE
Upcoming tonic upgrade

### ISSUE THREAD

**Issue by AmeliasCode** [yoshidan/google-cloud-rust#280]
Tonic has recently under gone a massive refactor to support hyper 1.0. This inevitably requires *some* effort to support. Fortunately, that effort is fairly low and mostly consists of updating dependencies and resynthesizing the googleapis generated code. I have a branch on my fork that does this already. 

Once the tonic update is released I can raise a PR, but this will be a breaking change and folks will have to either update their other dependencies *or*  _not_ update their google-cloud-* dependencies. 

What are your thoughts on how to best handle this?

**Comment by yoshidan** [comment]
I have checked the following fixes.

https://github.com/AmeliasCode/google-cloud-rust/compare/main..tonic-update

I think it is ok to update the dependency as the modification has been done to the extent of regenerating google-cloud-googleapis.

I will update tonic and see if there is a problem with the operation too.

**Comment by BeauGieskens** [comment]
Now that tonic [v0.12.0](https://github.com/hyperium/tonic/releases/tag/v0.12.0) is here, I'm keen to see it adopted by these libraries soon.

We're using google-cloud-pubsub in an Axum server and I think this update is the last thing stopping us from updating to the latest Axum version (with hyper 1.0 support).

**Comment by yoshidan** [comment]
https://github.com/yoshidan/google-cloud-rust/pull/283
We are currently checking for problems in the test environment. Will merge when completed.

**Comment by yoshidan** [comment]
Now I released [v0.28.0](https://crates.io/crates/google-cloud-pubsub)
