### ISSUE TITLE
Release version with tonic 0.11

### ISSUE THREAD

**Issue by MrCroxx** [yoshidan/google-cloud-rust#281]
Hi, @yoshidan .

Thank you for the lib. Currently I'm using google-cloud-pubsub and google-cloud-gax in my project. But the 0.17 version is till using tonic 0.10.2, which blocks me from upgrading other dependencies. Could you please release a new version with tonic 0.11? That helps a lot. 🙏

**Comment by yoshidan** [comment]
Now I published the new version!
