### ISSUE TITLE
PubSub ack failures with cancelled status

### ISSUE THREAD

**Issue by BeauGieskens** [yoshidan/google-cloud-rust#290]
We recently upgraded to the latest versions of these libraries to get the tonic 0.12 update:

```toml
google-cloud-gax = "0.19"
google-cloud-googleapis = "0.15"
google-cloud-pubsub = "0.28"
```

But we started encountering occasional failures where we would attempt to ack a PubSub message and get an error like so:

```text
status: Cancelled, message: "operation was canceled", details: [], metadata: MetadataMap { headers: {} }
```

So we enabled trace logging for this library and saw a little bit of a pattern:

```text
[2024-07-23T05:34:03.619Z DEBUG google_cloud_pubsub::subscriber] message received: msg_id=10262709005202018
[2024-07-23T05:34:03.619Z DEBUG google_cloud_pubsub::subscriber] message received: msg_id=10262709005202019
[2024-07-23T05:34:03.845Z ERROR my_crate::subscriber] Failed to ack PubSub message --- status: Cancelled, message: "operation was canceled", details: [], metadata: MetadataMap { headers: {} }
[2024-07-23T05:37:41.416Z TRACE google_cloud_pubsub::subscriber] start streaming: projects/my-project/subscriptions/my-sub
[2024-07-23T05:37:41.417Z TRACE google_cloud_pubsub::subscriber] reconnect - 'Status { code: Unavailable, message: "The StreamingPull stream closed for an expected reason and should be recreated, which is done automatically if using Cloud Pub/Sub client libraries. Refer to https://cloud.google.com/pubsub/docs/pull#streamingpull for more information.", source: None }' : projects/my-project/subscriptions/my-sub
[2024-07-23T05:39:48.344Z DEBUG google_cloud_pubsub::subscriber] message received: msg_id=10262709005202019
```

The pattern seems to be that we get the acknowledgment failure, then anywhere from 10 seconds to a few minutes later the subscriber seems to reconnect to the stream, with no messages received in the meantime. Ordered delivery is enabled for the subscription, which could explain the lack of messages after the failed acknowledgment. If it makes any difference, we have 3 subscriptions pulling at the same time, and we usually see all three of them follow this pattern simultaneously with each other. We're not doing anything too fancy with the messages, just pulling them and acking shortly after.

Rolling back to the previous release that used tonic 0.11 makes the problem go away. I'm happy to help by collecting additional logs somehow if it might help figure out what's going wrong.

**Comment by yoshidan** [comment]
I am facing the same problem, which seems to be caused by a closed connection on hyper during ack.
StreamingPull is expected to reconnect because the connection is closed periodically by Cloud Pub/Sub, but since there has never been a cancellation due to a closed connection on ack, I think that upgrading to tonic 0.12 is the cause of the problem. 

The cause is still under investigation, but we think it can be avoided by using a different gRPC connection for ack than for StreamingPull.

**Comment by yoshidan** [comment]
`google-cloud-pubsub = "0.28.1"` is released.
The relevant error will no longer occur here.

**Comment by aitvann** [comment]
I think I have similar issue. I see `error acknowledging message` in logs and logs about trying to reconnect. the issue only occurs when a queue I reading from is flooded with messages. could this be relevant to the error in this issue ?

**Comment by BeauGieskens** [comment]
We hit this issue again in the current version, and it does indeed appear to happen for us when the subscription we're pulling from has a lot of messages.

We implemented our own special retry mechanism based on the error code and what Google says we should do about it [in their docs](https://cloud.google.com/pubsub/docs/reference/error-codes). In our case this type of error happens many times a day, but only a single retry per failure has ever been needed so far to account for it.

This library supports giving a `google_cloud_gax::retry::RetrySetting` when you create a subscriber, the default of which doesn't catch the error code you're hitting. That's probably your easiest way to fix it right now.

**Comment by aitvann** [comment]
thanks a lot ! this seems to helped:
``` rust
let mut retry_settings = RetrySetting::default();
retry_settings
    .codes
    .push(google_cloud_gax::grpc::Code::Cancelled);
subscription
    .create(
        topic.fully_qualified_name(),
        subscription_config,
        retry_settings.into(),
    )
    .await?;
```

I wonder of side effects of it since `Code::Cancelled` is not included by default probably for a reason
