### ISSUE TITLE
Range requests on object download API

### ISSUE THREAD

**Issue by Elykz** [yoshidan/google-cloud-rust#30]
First of all, thanks a lot for all the work on this crate. It looks very promising ! :1st_place_medal: 

It seems the current google_cloud_storage::client::Client￼api does not allow Range 
requests for now. 

Google Cloud Storage documentation (https://cloud.google.com/storage/docs/xml-api/get-object-download) mentions:

`GET requests for objects can include a Range header as defined in the HTTP 1.1 RFC to limit the scope of the returned data within the object`

It would be nice if there was a way to supply a range header to the `download_object` and `download_streamed_object` http calls.

**Comment by yoshidan** [comment]
Thanks for your feedback. I added the feature now.
