### ISSUE TITLE
Duplicates when reading from google pub sub

### ISSUE THREAD

**Issue by hemanthk269** [yoshidan/google-cloud-rust#321]
we process pub sub messages in batches and call below iter method in a loop

iter method logic
1. Get the ack ids to ack from a storage.
2. Ack the messages that are read during previous iteration. (we set ack_timeout as 20 sec)
3. Get the around 10K messages from pub sub with 5 sec timeout.
4. store the ack ids in a storage (to ack in next iter).
5. send messages to caller for processing.

We are seeing duplicate messages once in a while (getting duplicates in 0-2 iterations per 100 iterations)
we are seeing duplicate in immediately next iteration not 2-4 iterations later (which is expected if ack is not done properly, ack_timeout is 20 sec and each iteration takes max 5 sec and in our testing it is only taking 2-3 sec)

also modified the code and check if the ack_ids are being nacked by library which will result in redelivery immediately, but that is also not the case, the messages for which we are receiving duplicates are not being nacked by library as well.

Unable to figure out the root cause of the duplicate messages.

We didn't enable exactly once delivery option for pub sub subscription as the through put is very less. (is this the root cause?)

**Comment by yoshidan** [comment]
Cloud pubsub is by default at least once, so it can be redistributed even after ack unless the actively once delivery option is enabled.
If you are concerned about the ack delay when exactly once delivery is specified as enabled, you will need to devise a way of not processing the same message ID in your application.
