### ISSUE TITLE
Unable to instantiate Client Struct

### ISSUE THREAD

**Issue by ragyibrahim** [yoshidan/google-cloud-rust#40]
### Issue
When running the below code block (from the readme) to instantiate Client struct
```rust 
let client = Client::default().await.unwrap();
```
I get the following error:

`GAX(Auth(HttpError(reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) })))`

I am using the `google_auth` crate from [this repository](https://github.com/hrvolapeter/gcp_auth) utilising the below code block to set the credentials (from the readme)

```rust
    let credentials_path = PathBuf::from("./src/keys/dev-key.json");
    let service_account = CustomServiceAccount::from_file(credentials_path).expect("Service account threw an error");
    let authentication_manager = AuthenticationManager::from(service_account);
    let scopes = &["https://www.googleapis.com/auth/cloud-platform"];
```

Setting the credentials seems to be working fine; when I run the code in debug, I can see the below all populating with the correct values

![main_rs_—_google_pubsub](https://user-images.githubusercontent.com/52903382/182085400-15f482ef-e100-47e4-83e1-5d5c76c4d53b.png)

### My environment

```bash
rustc --version
rustc 1.62.1 (e092d0b6b 2022-07-16)
```

```bash
cargo --version
cargo 1.62.1 (a748cf5a3 2022-06-08)
```

My `Cargo.toml` file looks like this:

```yaml
actix-web = "4.1.0"
awc = "3.0.0"
colored = "2.0.0"
dotenv = "0.15.0"
env_logger = "0.9.0"
futures = "0.3.21"
gcp_auth = "0.7.3"
google-cloud-gax = "0.7.0"
google-cloud-googleapis = {version = "0.4.0", features = ["pubsub"]}
google-cloud-pubsub = {version = "0.4.0", features = ["trace"]}
google_auth = "0.2.1"
prost-build = "0.10.4"
protobuf = "3.1.0"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
tokio = "1.20.1"
validator = "0.16.0"
validator_derive = "0.16.0"
```

**Comment by yoshidan** [comment]
google-cloud-spanner uses [google-cloud-auth](https://github.com/yoshidan/google-cloud-rust/tree/main/foundation/auth) and google-cloud-auth reads the credential file from `GOOGLE_APPLICATION_CREDENTIALS` outside of GCP.
When you set `GOOGLE_APPLICATION_CREDENTIALS` then it works fine.

```
export GOOGLE_APPLICATION_CREDENTIALS=/src/keys/dev-key.json
```

**Comment by yoshidan** [comment]
It seems the response from GCP is unexpected for google-cloud-auth.  
Would you send me "./src/keys/dev-key.json" to investigate this issue.

**Comment by ragyibrahim** [comment]
dev-key.json is the service account to access my GCP environment I can't send it to you. But to re-create the issue just replace that text with the path to your own local service account.

**Comment by yoshidan** [comment]
It works fine with my own service account file. The type of it is `service_account` and the structure is same as your `./src/keys/dev-key.json`.
  
Are you setting your file path into `GOOGLE_APPLICATION_CREDENTIALS` environment variable?
The `google-cloud-pubsub` uses [google-cloud-auth](https://github.com/yoshidan/google-cloud-rust/tree/main/foundation/auth) and google-cloud-auth read the credentials from `GOOGLE_APPLICATION_CREDENTIALS` when it runs outside the GCP.

**Comment by ragyibrahim** [comment]
all sorted now. Wasn't setting the credentials propley. For anyone else that runs into this issue, below is the code I used to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable when running the app locally.

```rust
let local = dotenv::var("local").unwrap_or("none".to_string());
    if local == String::from("true") {
        println!("==Running Locally==");
        // Get current working directory as owned string
        let current_dir = env::current_dir()
            .expect("Could not get current working directory")
            .to_str()
            .expect("Could not convert to str")
            .to_owned();
        println!("{:?}/src/keys/dev-key.json", current_dir.to_owned());
        // Concatenate string to form full path to key
        let _path_to_key = current_dir + "/src/keys/dev-key.json";
        // Take ownership of String and convert it to a &str
        let path_to_key = _path_to_key.as_str();
        println!("Path to key: {:?}", path_to_key);
        // Set GOOGLE_APPLICATION_CREDENTIALS env variable if working in a local env
        env::set_var("GOOGLE_APPLICATION_CREDENTIALS", path_to_key);
        println!(
            "GOOGLE_APPLICATION_CREDENTIALS: {}",
            dotenv::var("GOOGLE_APPLICATION_CREDENTIALS").unwrap_or("none".to_string())
        );
        // `credentials_path` variable is the path for the credentials `.json` file.
        let credentials_path = PathBuf::from(path_to_key);
        let service_account = CustomServiceAccount::from_file(credentials_path)
            .expect("Could not find Service account");
        let authentication_manager = AuthenticationManager::from(service_account);
        let scopes = &["https://www.googleapis.com/auth/cloud-platform"];
        let _token = authentication_manager
            .get_token(scopes)
            .await
            .expect("Token stuffed");
    }
```

Happy to close this now
