### ISSUE TITLE
[feature-request] [auth] Authorize without a credentials file

### ISSUE THREAD

**Issue by ditsuke** [yoshidan/google-cloud-rust#51]
I'm working on a Google pub/sub connector over at https://github.com/risingwavelabs/risingwave where sources can be added ad-hoc through a SQL interface. As such I feel it makes natural sense to not tie down credentials to files on the filesystem, but I don't think its possible yet with the `google-cloud-auth` crate. I can work on a PR to make this possible if it sounds good!

**Comment by yoshidan** [comment]
That's excellent! I would like to ask you.
Currently, `google-cloud-auth` acquires credentials from the metadata server on GCP environments such as GKE and Cloud Run, but credentials file is required in other environments.

**Comment by ditsuke** [comment]
please check #52 :octopus:
