### ISSUE TITLE
[pubsub] [feature-request] Support seeking subscriptions

### ISSUE THREAD

**Issue by ditsuke** [yoshidan/google-cloud-rust#53]
Pubsub supports a `subscription.seek` method to seek subscriptions back to a point in time or a saved snapshot. Can `google-cloud-pubsub` support this method to enable recovery mechanisms in applications?

**Comment by yoshidan** [comment]
Sorry for my late reply. 
As implemented in your PR it can be achieved by adding a method to `subscriber_client`.
