### ISSUE TITLE
Any support or help to implement this endpoint from Objects?

### ISSUE THREAD

**Issue by safwaan-menk** [yoshidan/google-cloud-rust#86]
I want to be able to get all the objects from a particular bucket like the below documentation

https://cloud.google.com/storage/docs/json_api/v1/objects/list

Can this be implemented? I am trying to add it to the current code, but I need some help understanding how to go about this

**Comment by yoshidan** [comment]
I think this is the API you want.
https://github.com/yoshidan/google-cloud-rust/blob/main/storage/src/http/storage_client.rs#L1695

**Comment by safwaan-menk** [comment]
Yes thank you, this is exactly what I was looking for!

> I think this is the API you want. https://github.com/yoshidan/google-cloud-rust/blob/main/storage/src/http/storage_client.rs#L1695
